AutoShop.WebUI/Controllers/AutoshopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Autoshop.Domain;
using Autoshop.Infrastructure;

namespace Autoshop.Web.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AutoshopController : Controller
    {
        private CarShopContext db = new CarShopContext();

        // GET: Autoshop
        public ActionResult Index()
        {
            return View();
        }

        // GET: Autoshop/Manufacturers
        public ActionResult Manufacturers()
        {
            var manufacturers = db.Manufacturers.ToList();
            return View(manufacturers);
        }

        // GET: Autoshop/ManufacturerDetails/5
        public ActionResult ManufacturerDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // GET: Autoshop/CreateManufacturer
        public ActionResult CreateManufacturer()
        {
            return View();
        }

        // POST: Autoshop/CreateManufacturer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateManufacturer([Bind(Include = "ManufacturerId,Name")] Manufacturer manufacturer)
        {
            if (ModelState.IsValid)
            {
                db.Manufacturers.Add(manufacturer);
                db.SaveChanges();
                return RedirectToAction("Manufacturers");
            }

            return View(manufacturer);
        }

        // GET: Autoshop/EditManufacturer/5
        public ActionResult EditManufacturer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // POST: Autoshop/EditManufacturer/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditManufacturer([Bind(Include = "ManufacturerId,Name")] Manufacturer manufacturer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(manufacturer).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Manufacturers");
            }
            return View(manufacturer);
        }

        // GET: Autoshop/DeleteManufacturer/5
        public ActionResult DeleteManufacturer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // POST: Autoshop/DeleteManufacturer/5
        [HttpPost, ActionName("DeleteManufacturer")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteManufacturerConfirmed(int id)
        {
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            db.Manufacturers.Remove(manufacturer);
            db.SaveChanges();
            return RedirectToAction("Manufacturers");
        }

        // GET: Autoshop/Cars
        public ActionResult Cars()
        {
            var cars = db.Cars.Include("Manufacturer").ToList();
            return View(cars);
        }

        // GET: Autoshop/CarDetails/5
        public ActionResult CarDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Include("Manufacturer").FirstOrDefault(c => c.CarId == id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // GET: Autoshop/CreateCar
        public ActionResult CreateCar()
        {
            ViewBag.ManufacturerId = new SelectList(db.Manufacturers, "ManufacturerId", "Name");
            return View();
        }

        // POST: Autoshop/CreateCar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCar([Bind(Include = "CarId,Model,ManufacturerId")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Cars");
            }

            ViewBag.ManufacturerId = new SelectList(db.Manufacturers, "ManufacturerId", "Name", car.ManufacturerId);
            return View(car);
        }

        // GET: Autoshop/EditCar/5
        public ActionResult EditCar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            ViewBag.ManufacturerId = new SelectList(db.Manufacturers, "ManufacturerId", "Name", car.ManufacturerId);
            return View(car);
        }

        // POST: Autoshop/EditCar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCar([Bind(Include = "CarId,Model,ManufacturerId")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Cars");
            }
            ViewBag.ManufacturerId = new SelectList(db.Manufacturers, "ManufacturerId", "Name", car.ManufacturerId);
            return View(car);
        }

        // GET: Autoshop/DeleteCar/5
        public ActionResult DeleteCar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Autoshop/DeleteCar/5
        [HttpPost, ActionName("DeleteCar")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCarConfirmed(int id)
        {
            Car car = db.Cars.Find(id);
            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Cars");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoShop.WebUI/Views/Autoshop/CarDetails.cshtml
@model Autoshop.Domain.Car

@{
ViewBag.Title = "Car Details";
Layout = "../Shared/_AdminLayout.cshtml";
}

<h2>Car Details</h2>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Model)</dt>
        <dd>@Html.DisplayFor(model => model.Model)</dd>
        <dt>@Html.DisplayNameFor(model => model.Manufacturer.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Manufacturer.Name)</dd>
    </dl>
</div>

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</div>

AutoShop.WebUI/Views/Autoshop/Cars.cshtml
@model IEnumerable<Autoshop.Domain.Car>

@{
ViewBag.Title = "Cars";
Layout = "../Shared/_AdminLayout.cshtml";
}

<h2>Cars</h2>

<div class="mb-4">
    @Html.ActionLink("Create New", "CreateCar", null, new { @class = "btn btn-primary", @title = "Create a new car" })
</div>

<table class="table table-dark table-striped table-hover">
    <thead>
    <tr>
        <th>Model</th>
        <th>Manufacturer</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.Model)</td>
        <td>@Html.DisplayFor(modelItem => item.Manufacturer.Name)</td>
        <td>
            @Html.ActionLink("Details", "CarDetails", new { id = item.CarId }, new { @class = "btn btn-info btn-sm", @title = "View details" }) |
            @Html.ActionLink("Edit", "EditCar", new { id = item.CarId }, new { @class = "btn btn-warning btn-sm", @title = "Edit this car" }) |
            @Html.ActionLink("Delete", "DeleteCar", new { id = item.CarId }, new { @class = "btn btn-danger btn-sm", @title = "Delete this car" })
        </td>
    </tr>
    }
    </tbody>
</table>

<!-- Additional section about sales and customer interaction -->
<div class="card mt-4 bg-dark text-white">
    <div class="card-header bg-primary text-white">
        Sales and Customer Interaction
    </div>
    <div class="card-body">
        <h5 class="card-title">Boost Your Car Sales</h5>
        <p class="card-text">
            Effective sales techniques and excellent customer service are key to a successful car dealership. Here are some tips to help you enhance your sales:
        </p>
        <ul>
            <li>Understand your customer's needs and preferences.</li>
            <li>Provide detailed and accurate information about each car.</li>
            <li>Offer test drives to let customers experience the car firsthand.</li>
            <li>Follow up with potential buyers and provide personalized assistance.</li>
            <li>Ensure a smooth and transparent purchasing process.</li>
        </ul>
        <p class="card-text">
            Remember, building strong relationships with your customers can lead to repeat business and referrals. Keep in touch with your customers even after the sale to ensure their satisfaction and address any concerns they might have.
        </p>
        <a href="mailto:support@autoshop.com" class="btn btn-secondary">Contact Support</a>
    </div>
</div>

AutoShop.WebUI/Views/Autoshop/CreateCar.cshtml
@model Autoshop.Domain.Car

@{
ViewBag.Title = "Create Car";
Layout = "../Shared/_AdminLayout.cshtml";
}

<h2>Create Car</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Car</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter car model" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ManufacturerId, "Manufacturer", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ManufacturerId", null, htmlAttributes: new { @class = "form-control", @title = "Select the manufacturer" })
            @Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</div>

AutoShop.WebUI/Views/Autoshop/CreateManufacturer.cshtml
@model Autoshop.Domain.Manufacturer

@{
ViewBag.Title = "Create Manufacturer";
Layout = "../Shared/_AdminLayout.cshtml";
}

<h2>Create Manufacturer</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Manufacturer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</div>

AutoShop.WebUI/Views/Autoshop/DeleteCar.cshtml
@model Autoshop.Domain.Car

@{
    ViewBag.Title = "Delete Car";
    Layout = "../Shared/_AdminLayout.cshtml";
}

<h2>Delete Car</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Model)</dt>
        <dd>@Html.DisplayFor(model => model.Model)</dd>
        <dt>@Html.DisplayNameFor(model => model.Manufacturer.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Manufacturer.Name)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
        </div>
    }
    }
</div>

AutoShop.WebUI/Views/Autoshop/DeleteManufacturer.cshtml
@model Autoshop.Domain.Manufacturer

@{
ViewBag.Title = "Manufacturer Details";
Layout = "../Shared/_AdminLayout.cshtml";

}

<h2>Manufacturer Details</h2>

<div>
    <h4>Manufacturer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</p>

AutoShop.WebUI/Views/Autoshop/EditCar.cshtml
@model Autoshop.Domain.Car

@{
    ViewBag.Title = "Edit Car";
    Layout = "../Shared/_AdminLayout.cshtml";
}

<h2>Edit Car</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.CarId)

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter car model" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManufacturerId, "Manufacturer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManufacturerId", null, htmlAttributes: new { @class = "form-control", @title = "Select the manufacturer" })
                @Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</div>

AutoShop.WebUI/Views/Autoshop/EditManufacturer.cshtml
@model Autoshop.Domain.Manufacturer

@{
ViewBag.Title = "Edit Manufacturer";
Layout = "../Shared/_AdminLayout.cshtml";

}

<h2>Edit Manufacturer</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Manufacturer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.ManufacturerId)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</div>

AutoShop.WebUI/Views/Autoshop/Index.cshtml
@{
    ViewBag.Title = "Autoshop Home";
    Layout = "../Shared/_AdminLayout.cshtml";
}

<h2 class="mb-4">Autoshop Administration</h2>

<div class="row">
    <div class="col-md-6">
        <div class="card bg-dark text-white mb-4">
            <div class="card-body text-center">
                <i class="fas fa-industry fa-3x mb-3"></i>
                <h4 class="card-title">Manage Manufacturers</h4>
                <p class="card-text">Add, edit, or remove car manufacturers from your inventory.</p>
                <a href="@Url.Action("Manufacturers", "Autoshop")" class="btn btn-primary">Go to Manufacturers</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card bg-dark text-white mb-4">
            <div class="card-body text-center">
                <i class="fas fa-car fa-3x mb-3"></i>
                <h4 class="card-title">Manage Cars</h4>
                <p class="card-text">Add, edit, or remove cars from your inventory.</p>
                <a href="@Url.Action("Cars", "Autoshop")" class="btn btn-primary">Go to Cars</a>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

AutoShop.WebUI/Views/Autoshop/ManufacturerDetails.cshtml
@model Autoshop.Domain.Manufacturer

@{
    ViewBag.Title = "Manufacturer Details";
    Layout = "../Shared/_AdminLayout.cshtml";

}

<h2>Manufacturer Details</h2>

<div>
    <h4>Manufacturer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</p>

AutoShop.WebUI/Views/Autoshop/Manufacturers.cshtml
@model IEnumerable<Autoshop.Domain.Manufacturer>

@{
ViewBag.Title = "Manufacturers";
Layout = "../Shared/_AdminLayout.cshtml";
}

<h2 class="text-light">Manufacturers</h2>

<p>
    @Html.ActionLink("Create New", "CreateManufacturer", null, new { @class = "btn btn-primary" })
</p>

<div class="table-responsive">
    <table class="table table-dark table-striped table-hover">
        <thead>
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>
                @Html.ActionLink("Details", "ManufacturerDetails", new { id = item.ManufacturerId }, new { @class = "btn btn-info btn-sm" }) |
                @Html.ActionLink("Edit", "EditManufacturer", new { id = item.ManufacturerId }, new { @class = "btn btn-warning btn-sm" }) |
                @Html.ActionLink("Delete", "DeleteManufacturer", new { id = item.ManufacturerId }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
        }
        </tbody>
    </table>
</div>

<style>
    h2 {
        margin-bottom: 20px;
    }

    .btn {
        margin-right: 5px;
    }
</style>